# Generated by Django 4.2 on 2023-04-25 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='uploaded',
            new_name='author',
        ),
    ]
